"""
Request entity for FaceMergeRequest information.
"""

from baiducloud_python_sdk_core.abstract_model import AbstractModel


class FaceMergeRequest(AbstractModel):
    """
    Request entity for FaceMergeRequest operation.

    This class encapsulates all parameters for the API request.
    """

    def __init__(
        self, image_template, image_target, version=None, alpha=None, merge_degree=None, position=None, language=None
    ):
        """
        Initialize FaceMergeRequest request entity.

        :param version: 服务版本，可选1.0/2.0/3.0/4.0，默认1.0。推荐2.0融合效果，3.0清晰度更高，4.0为最新版本
        :type version: str (optional)

        :param alpha: alpha parameter
        :type alpha: float (optional)

        :param image_template: image_template parameter
        :type image_template: str (required)

        :param image_target: image_target parameter
        :type image_target: str (required)

        :param merge_degree: 融合度，越高则融合图与目标图越相似
        :type merge_degree: str (optional)

        :param position: 水印位置：0-右下角，1-左下角，2-左上角，3-右上角，默认0
        :type position: int (optional)

        :param language: 水印语言：0-中文（AI生成），1-英文（Generated by AI），默认0
        :type language: int (optional)
        """
        super().__init__()
        self.version = version
        self.alpha = alpha
        self.image_template = image_template
        self.image_target = image_target
        self.merge_degree = merge_degree
        self.position = position
        self.language = language

    def to_dict(self):
        """
        Convert the request entity to a dictionary representation.

        Nested model objects are recursively converted to dictionaries.

        :return: Dictionary representation of the request
        :rtype: dict
        """
        _map = super().to_dict()
        if _map is not None:
            return _map
        result = dict()
        if self.version is not None:
            result['version'] = self.version
        if self.alpha is not None:
            result['alpha'] = self.alpha
        if self.image_template is not None:
            result['image_template'] = self.image_template
        if self.image_target is not None:
            result['image_target'] = self.image_target
        if self.merge_degree is not None:
            result['merge_degree'] = self.merge_degree
        if self.position is not None:
            result['position'] = self.position
        if self.language is not None:
            result['language'] = self.language
        return result

    def from_dict(self, m):
        """
        Populate the request entity from a dictionary.

        Nested dictionaries are recursively converted to model objects.

        :param m: Dictionary containing request data
        :type m: dict

        :return: Self reference for method chaining
        :rtype: FaceMergeRequest

        :raises TypeError: If input is not a dictionary or field type mismatch
        :raises ValueError: If nested model conversion fails
        """
        m = m or dict()
        if m.get('version') is not None:
            self.version = m.get('version')
        if m.get('alpha') is not None:
            self.alpha = m.get('alpha')
        if m.get('image_template') is not None:
            self.image_template = m.get('image_template')
        if m.get('image_target') is not None:
            self.image_target = m.get('image_target')
        if m.get('merge_degree') is not None:
            self.merge_degree = m.get('merge_degree')
        if m.get('position') is not None:
            self.position = m.get('position')
        if m.get('language') is not None:
            self.language = m.get('language')
        return self
