"""
Models for privatezone SDK.
"""

from .add_parsing_records_request import AddParsingRecordsRequest
from .add_parsing_records_response import AddParsingRecordsResponse
from .associate_vpc_request import AssociateVpcRequest
from .create_a_private_zone_request import CreateAPrivateZoneRequest
from .create_a_private_zone_response import CreateAPrivateZoneResponse
from .disassociate_vpc_request import DisassociateVpcRequest
from .modify_parsing_records_request import ModifyParsingRecordsRequest
from .private_record import PrivateRecord
from .private_zone import PrivateZone
from .query_and_parse_record_list_response import QueryAndParseRecordListResponse
from .query_the_list_of_private_zones_response import QueryTheListOfPrivateZonesResponse
from .search_for_details_of_privatzone_response import SearchForDetailsOfPrivatzoneResponse
from .vpc import Vpc
from .query_the_list_of_private_zones_request import QueryTheListOfPrivateZonesRequest
from .search_for_details_of_privatzone_request import SearchForDetailsOfPrivatzoneRequest
from .set_parsing_record_status_request import SetParsingRecordStatusRequest
from .delete_private_zone_request import DeletePrivateZoneRequest
from .delete_parsing_records_request import DeleteParsingRecordsRequest
from .query_and_parse_record_list_request import QueryAndParseRecordListRequest
