"""
Models for oos SDK.
"""

from .allowed_failure_control import AllowedFailureControl
from .category import Category
from .check_template_v2_request import CheckTemplateV2Request
from .check_template_v2_response import CheckTemplateV2Response
from .create_execution_v2_request import CreateExecutionV2Request
from .create_execution_v2_response import CreateExecutionV2Response
from .create_template_v2_request import CreateTemplateV2Request
from .create_template_v2_response import CreateTemplateV2Response
from .cron_execution import CronExecution
from .dag_action_model import DagActionModel
from .dag_instance import DagInstance
from .dag_spec import DagSpec
from .delete_template_v2_response import DeleteTemplateV2Response
from .event import Event
from .event_execution import EventExecution
from .event_model import EventModel
from .execution import Execution
from .execution_page import ExecutionPage
from .execution_task_summary import ExecutionTaskSummary
from .get_execution_detail_v2_response import GetExecutionDetailV2Response
from .get_execution_list_v2_request import GetExecutionListV2Request
from .get_execution_list_v2_response import GetExecutionListV2Response
from .get_operator_list_v2_request import GetOperatorListV2Request
from .get_operator_list_v2_response import GetOperatorListV2Response
from .get_task_children_list_v2_request import GetTaskChildrenListV2Request
from .get_task_children_list_v2_response import GetTaskChildrenListV2Response
from .get_task_detail_v2_response import GetTaskDetailV2Response
from .get_template_detail_v2_response import GetTemplateDetailV2Response
from .get_template_list_v2_request import GetTemplateListV2Request
from .get_template_list_v2_response import GetTemplateListV2Response
from .input_model import InputModel
from .key_value_pair import KeyValuePair
from .link_model import LinkModel
from .log import Log
from .loop_model import LoopModel
from .model_property import ModelProperty
from .operator import Operator
from .operator_page import OperatorPage
from .operator_spec import OperatorSpec
from .option import Option
from .output_model import OutputModel
from .parallelism_control import ParallelismControl
from .period import Period
from .resource import Resource
from .tag import Tag
from .tag_expression import TagExpression
from .tag_selector import TagSelector
from .task import Task
from .task_children_page import TaskChildrenPage
from .task_operator_summary import TaskOperatorSummary
from .template import Template
from .template_page import TemplatePage
from .update_template_v2_request import UpdateTemplateV2Request
from .update_template_v2_response import UpdateTemplateV2Response
from .delete_template_v2_request import DeleteTemplateV2Request
from .get_execution_detail_v2_request import GetExecutionDetailV2Request
from .get_task_detail_v2_request import GetTaskDetailV2Request
from .get_template_detail_v2_request import GetTemplateDetailV2Request
