"""
Models for dns SDK.
"""

from .add_domain_name_request import AddDomainNameRequest
from .add_line_group_request import AddLineGroupRequest
from .add_parsing_records_request import AddParsingRecordsRequest
from .billing import Billing
from .billing_for_renew import BillingForRenew
from .domain_name_renewal_request import DomainNameRenewalRequest
from .line import Line
from .modify_parsing_records_request import ModifyParsingRecordsRequest
from .public_record import PublicRecord
from .public_zone import PublicZone
from .purchase_a_paid_domain_name_request import PurchaseAPaidDomainNameRequest
from .query_and_parse_record_list_response import QueryAndParseRecordListResponse
from .query_domain_name_list_response import QueryDomainNameListResponse
from .query_the_list_of_line_groups_response import QueryTheListOfLineGroupsResponse
from .reservation import Reservation
from .tag_model import TagModel
from .update_line_group_request import UpdateLineGroupRequest
from .upgrade_the_free_domain_name_to_the_universal_version_request import (
    UpgradeTheFreeDomainNameToTheUniversalVersionRequest,
)
from .modify_the_parsing_record_status_request import ModifyTheParsingRecordStatusRequest
from .query_the_list_of_line_groups_request import QueryTheListOfLineGroupsRequest
from .delete_parsing_records_request import DeleteParsingRecordsRequest
from .query_domain_name_list_request import QueryDomainNameListRequest
from .remove_domain_name_request import RemoveDomainNameRequest
from .delete_line_group_request import DeleteLineGroupRequest
from .query_and_parse_record_list_request import QueryAndParseRecordListRequest
