"""
Models for aigw SDK.
"""

from .consumer_credential_info import ConsumerCredentialInfo
from .consumer_credential_location import ConsumerCredentialLocation
from .consumer_credential_spec import ConsumerCredentialSpec
from .consumer_detail_info import ConsumerDetailInfo
from .consumer_summary import ConsumerSummary
from .cors_policy import CorsPolicy
from .create_consumer_request import CreateConsumerRequest
from .create_consumer_response import CreateConsumerResponse
from .create_route_request import CreateRouteRequest
from .create_route_response import CreateRouteResponse
from .credential_op import CredentialOp
from .custom_header import CustomHeader
from .delete_consumer_response import DeleteConsumerResponse
from .delete_route_response import DeleteRouteResponse
from .delete_route_result import DeleteRouteResult
from .fallback_config import FallbackConfig
from .get_consumer_list_response import GetConsumerListResponse
from .get_consumer_response import GetConsumerResponse
from .iam_credential_spec import IAMCredentialSpec
from .match_rule import MatchRule
from .match_rules import MatchRules
from .matcher_rule import MatcherRule
from .origin_match import OriginMatch
from .origin_rule import OriginRule
from .path_rule import PathRule
from .query_routing_details_response import QueryRoutingDetailsResponse
from .query_routing_list_response import QueryRoutingListResponse
from .regex_rewrite import RegexRewrite
from .regex_rewrite_config import RegexRewriteConfig
from .request_rate_limit import RequestRateLimit
from .request_rate_limit_rule import RequestRateLimitRule
from .response_headers import ResponseHeaders
from .retry_policy import RetryPolicy
from .rewrite import Rewrite
from .rewrite_config import RewriteConfig
from .route_list_page import RouteListPage
from .route_match_path import RouteMatchPath
from .route_result import RouteResult
from .route_summary import RouteSummary
from .rule_item import RuleItem
from .tag import Tag
from .target_service import TargetService
from .timeout_policy import TimeoutPolicy
from .token_limit_config import TokenLimitConfig
from .token_rate_limit import TokenRateLimit
from .token_rate_limit_rule import TokenRateLimitRule
from .update_consumer_request import UpdateConsumerRequest
from .update_consumer_response import UpdateConsumerResponse
from .update_route_request import UpdateRouteRequest
from .update_route_response import UpdateRouteResponse
from .query_routing_details_request import QueryRoutingDetailsRequest
from .delete_route_request import DeleteRouteRequest
from .get_consumer_request import GetConsumerRequest
from .delete_consumer_request import DeleteConsumerRequest
from .query_routing_list_request import QueryRoutingListRequest
from .get_consumer_list_request import GetConsumerListRequest
